# Generated by Django 2.2.6 on 2019-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
    ]
